In [4]:
import numpy as np

data=np.load('data.npy')
target=np.load('target.npy')

#loading the save numpy arrays in the previous code

from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,
                                                              test_size=0.1)


In [5]:
from sklearn.svm import SVC

algorithm = SVC()
algorithm.fit(train_data,train_target)
predicted_target = algorithm.predict(test_data)


print("Actual Target : ",test_target)
print("Predicted Target :",predicted_target)


from sklearn.metrics import accuracy_score

acc = accuracy_score(test_target,predicted_target)
print("Accuracy : ",acc)

Actual Target :  [0 3 2 1 2 0 0 0 2 1 2 2 1 0 3 1 1 3 2 3 0 0 2 3 1 0 2 1 0 0 0 2 1 1 2 1 1
 1 2 0 2 1 0 3 0 2 0 0 1 0 1]
Predicted Target : [2 3 2 2 2 0 0 2 2 2 2 2 1 2 3 2 2 3 2 3 2 2 2 3 2 0 2 2 2 0 2 1 2 2 2 2 2
 1 2 0 2 1 0 3 0 2 0 0 2 0 2]
Accuracy :  0.6078431372549019


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [6]:

from sklearn.metrics import classification_report,confusion_matrix
#https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781838555078/6/ch06lvl1sec34/confusion-matrix
#cm=confusion_matrix(y_test,y_pred_class)
cm=confusion_matrix(test_target,predicted_target)
print(cm)

[[10  0  7  0]
 [ 0  3 12  0]
 [ 0  1 12  0]
 [ 0  0  0  6]]
