In [6]:
import cv2
import os
# for file operation
datapath = 'MangoImages'

# get all directories names in to list
labels = os.listdir(datapath)
#os.mkdir('myfolder')
print(labels)

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
label_dict = {}
for i in range(len(labels)):
    label_dict[labels[i]]= i
print(label_dict)

['G1', 'G2', 'G3', 'G4']
{'G1': 0, 'G2': 1, 'G3': 2, 'G4': 3}


In [7]:
data=[]
target=[]

In [8]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
import statistics

In [9]:
def statistical_feature(img,label):
    #image = cv2.imread(img)
    image=cv2.resize(img,(376,251))
    ore = image.copy()
    ore2 = image.copy()
    ore3 = image.copy()
    ore5 = image.copy()
    ore6 = image.copy()
    ore7 = image.copy()
    ######### No need ############
    #ore4 = image.copy()
    ##############################

    rows,cols,channels = image.shape

    original = image.copy()
    image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    lower = np.array([22, 93, 0], dtype="uint8")
    upper = np.array([45, 255, 255], dtype="uint8")
    orgmask = cv2.inRange(image, lower, upper)



    mask = cv2.GaussianBlur(orgmask,(5,5),0)


    cnts = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = cnts[0] if len(cnts) == 2 else cnts[1]
    cv2.drawContours(ore2, cnts, -1, (0,255,0),3)

    ############ No need ###############
    #cntsTest = cv2.findContours(orgmask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    #cntsTest = cntsTest[0] if len(cntsTest) == 2 else cntsTest[1]
    #cv2.drawContours(ore4, cntsTest, -1, (0,255,0),3)
    ####################################

    for c in cnts:
        if(cv2.contourArea(c) > 700):
            selectedContour = c
            x,y,w,h = cv2.boundingRect(c)
            cv2.rectangle(ore3, (x, y), (x + w, y + h), (36,255,12), 2)

    for i in range(rows):
        for j in range(cols):
            if cv2.pointPolygonTest(selectedContour,(j, i),True)<0:
                 original[i, j]= (0, 0, 0)
                #dist = cv2.pointPolygonTest(cnt,(50,50),True)
            else:
                original[i, j]= (255, 255, 255)


    #+++++++++++ openning ++++++++++++++++++++++++++++++++++++
    originalOpen = original.copy()
    kernel = np.ones((17,17),np.uint8)
    originalOpenning = cv2.morphologyEx(originalOpen, cv2.MORPH_OPEN, kernel)
    
    #cv2.imshow('opening', originalOpenning)
    #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    print(mask)
    print(originalOpenning)

    originalOpenning = cv2.cvtColor(originalOpenning, cv2.COLOR_BGR2GRAY)

    originalOpenning = cv2.GaussianBlur(originalOpenning,(3,3),0)

    cnts2 = cv2.findContours(originalOpenning, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts2 = cnts2[0] if len(cnts2) == 2 else cnts2[1]
    cv2.drawContours(ore5, cnts2, -1, (0,255,0),3)

    for c in cnts2:
        if(cv2.contourArea(c) > 700):
            selectedContour = c
            x,y,w,h = cv2.boundingRect(c)
            cv2.rectangle(ore6, (x, y), (x + w, y + h), (36,255,12), 2)

    #$$$$$$$$$$$$$$$$$$$$ hist $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    rVal =[]
    bVal =[]
    gVal =[]
    YCrCb_YVal = []

    ######CrCb -> b ######
    BGR2YCrCb = ore7.copy()
    YCrCb = cv2.cvtColor(BGR2YCrCb, cv2.COLOR_BGR2YCrCb)
    Y, Cr, Cb  = cv2.split(YCrCb)
    YCrCb_Y = Y
    ######################

    b, g, r = cv2.split(ore7)
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    for i in range(rows):
        for j in range(cols):
            if cv2.pointPolygonTest(selectedContour,(j, i),True)<0:
                ore7[i, j]= (255, 255, 255)
                #dist = cv2.pointPolygonTest(cnt,(50,50),True)
            else:
                #$$$$$$$$$$$$$$$$$$ hist $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
                rVal.append(int(r[i][j]))
                bVal.append(int(b[i][j]))
                gVal.append(int(g[i][j]))
                YCrCb_YVal.append(int(YCrCb_Y[i][j]))
                #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


    #cv2.imshow('1) image', ore)
    #cv2.imshow('2) HSV', image)
    #cv2.imshow('3) orgmask', orgmask)
    #cv2.imshow('4) mask', mask)
    #cv2.imshow('5) findContours', ore2)
    #cv2.imshow('6) contourArea(c) > 700', ore3)
    #cv2.imshow('7) pre...', original)
    ################## No need ###################
    #cv2.imshow('8) No need-> without smooting the mask ', ore4)
    ##############################################
    #cv2.imshow('9) pre...Final after openning contour ', ore5)
    #cv2.imshow('10) pre...Final after openning rec ', ore6)
    #cv2.imshow('11) pre...Final after openning  ', ore7)


    #$$$$$$$$$$$$$$$ CNN $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    #CNNimg = ore7.copy()
    #img = cv2.cvtColor(CNNimg, cv2.COLOR_BGR2YCrCb)
    #b, g, r = cv2.split(img)
    #CNNimg = b
    #cv2.imshow('12) For CNN  ', CNNimg)
   
    #CNNimgGaus = CNNimg
    #cv2.imshow('13) CNNimgGaus  ', CNNimgGaus)
    # convolute with proper kernels
    #CNNimgLOG = cv2.Laplacian(CNNimgGaus,cv2.CV_64F, ksize = 3)  
    #cv2.imshow('14) CNNimgLOG  ', CNNimgLOG)
    #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

    #YYYYYYYYYYYYYYYYYYY K-Means YYYYYYYYYYYYYYYYYYYYYYY
    #ore8 = ore7.copy()
    #mask2 = CNNimg.copy()
    #(height,width)=mask2.shape[:2]
    #flat_array=mask2.reshape((height*width,1))

    #from sklearn.cluster import KMeans
    #clsfr=KMeans(n_clusters=3)

    #clsfr.fit(flat_array)
    #labels=clsfr.labels_
    #labels_2d=labels.reshape((height,width))
    #for i in range(height):
     #   for j in range(width):

      #      if(labels_2d[i][j]==0):
       #         ore8[i][j]=[255,0,0]
        #    elif(labels_2d[i][j]==1):
         #       ore8[i][j]=[0,255,0]
          #  elif(labels_2d[i][j]==2):
           #     ore8[i][j]=[0,0,255]
            #elif(labels_2d[i][j]==3):
             #   ore8[i][j]=[0,0,0]

   # cv2.imshow('12) Calxy detection  ', ore8)            

    ##################### Hist ##########################


   # b, g, r = cv2.split(ore7)
   # print("Tesing 1 ")
   # print(b)
   # print(b[0][1])
   # print(len(r.ravel()))
   # print(len(rVal))
   # print(rVal)
    #plt.hist(r.ravel(), 256, [0, 250])
    #plt.hist(g.ravel(), 256, [0, 250])
    #plt.hist(b.ravel(), 256, [0, 250])
    #plt.hist( rVal, 256, [0, 256])
    #plt.hist( gVal, 256, [0, 256])
    #plt.hist( bVal, 256, [0, 256])
    ######CrCb -> b ###### to reduce shining issue
    #plt.hist( YCrCb_YVal, 256, [0, 256])
    ######################
    #plt.show()
    #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    rm = statistics.mean(rVal)
    rsd = statistics.stdev(rVal)
    #print("(R)Mean  : ",rm)
    #print("(R)Standard Deviation of Sample set is " ,rsd)

    gm = statistics.mean(gVal)
    gsd = statistics.stdev(gVal)
    #print("(G)Mean  : ",gm)
    #print("(G)Standard Deviation of Sample set is " ,gsd)

    bm = statistics.mean(bVal)
    bsd = statistics.stdev(bVal)
    #print("(B)Mean  : ",bm)
    #print("(B)Standard Deviation of Sample set is " ,bsd)

    ##########CrCb -> b#############  to reduce shining issue
    YCrCb_Ym = statistics.mean(YCrCb_YVal)
    YCrCb_Ysd = statistics.stdev(YCrCb_YVal)
    #print("(YCrCb_Y)Mean  : ",YCrCb_Ym)
    #print("(YCrCb_Y)Standard Deviation of Sample set is " ,YCrCb_Ysd)
    ################################

    #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

    #cv2.waitKey()
    data.append([rm,rsd,gm,gsd,bm,bsd,YCrCb_Ym,YCrCb_Ysd])
    target.append(label)

In [10]:
for label in labels:
    imgs_path = os.path.join(datapath,label)
    imgs_names = os.listdir(imgs_path)
    print(imgs_path)
    print(imgs_names)
    print("------------------------------------------------------")

    for img_name in imgs_names:
        
        img_path = os.path.join(imgs_path,img_name)
        img = cv2.imread(img_path)

        #cv2.imshow('LIVE',img)
        #cv2.waitKey(100)

        statistical_feature(img,label_dict[label])


print(data)
print(target)

#$$$$$$$$$$$$$$$$$$$$$$$$ Save data in to physical file $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
import numpy as np
np.save('data',data)
np.save('target',target)

MangoImages\G1
['DSC_0429.jpg', 'DSC_0435.jpg', 'DSC_0441.jpg', 'DSC_0447.jpg', 'DSC_0453.jpg', 'DSC_0459.jpg', 'DSC_0465.jpg', 'DSC_0471.jpg', 'DSC_0477.jpg', 'DSC_0483.jpg', 'DSC_0489.jpg', 'DSC_0495.jpg', 'DSC_0501.jpg', 'DSC_0507.jpg', 'DSC_0513.jpg', 'DSC_0519.jpg', 'DSC_0525.jpg', 'DSC_0531.jpg', 'DSC_0537.jpg', 'DSC_0543.jpg', 'DSC_0549.jpg', 'DSC_0555.jpg', 'DSC_0561.jpg', 'DSC_0567.jpg', 'DSC_0573.jpg', 'DSC_0579.jpg', 'DSC_0592.jpg', 'DSC_0598.jpg', 'DSC_0604.jpg', 'DSC_0610.jpg', 'DSC_0616.jpg', 'DSC_0622.jpg', 'DSC_0630.jpg', 'DSC_0637.jpg', 'DSC_0643.jpg', 'DSC_0649.jpg', 'DSC_0655.jpg', 'DSC_0661.jpg', 'DSC_0667.jpg']
------------------------------------------------------
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

